name: Node.js Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install
    - run: yarn build
    - name: Publish to NPM
      run: yarn publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # npm-dist-tag
    # https://docs.npmjs.com/cli/v7/commands/npm-dist-tag
    - name: Ensure dist-tag published
      run: |
        npm i -g zx
        zx .github/scripts/npm-dist-tag.mjs
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    # Publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
    - name: Publish to GitHub Package Registry
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
